"""add indexes to fk columns

Revision ID: bb5db4bc1d31
Revises: b8b02d856bc9
Create Date: 2025-06-26 00:34:17.219446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5db4bc1d31'
down_revision: Union[str, None] = 'b8b02d856bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_item_splits_item_id'), 'item_splits', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_splits_user_id'), 'item_splits', ['user_id'], unique=False)
    op.drop_constraint('item_splits_user_id_fkey', 'item_splits', type_='foreignkey')
    op.drop_constraint('item_splits_item_id_fkey', 'item_splits', type_='foreignkey')
    op.create_foreign_key(None, 'item_splits', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item_splits', 'users', ['user_id'], ['uid'], ondelete='CASCADE')
    op.create_index(op.f('ix_items_payment_id'), 'items', ['payment_id'], unique=False)
    op.drop_constraint('items_payment_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'payments', ['payment_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_payment_payers_payment_id'), 'payment_payers', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_payers_user_id'), 'payment_payers', ['user_id'], unique=False)
    op.drop_constraint('payment_payers_payment_id_fkey', 'payment_payers', type_='foreignkey')
    op.drop_constraint('payment_payers_user_id_fkey', 'payment_payers', type_='foreignkey')
    op.create_foreign_key(None, 'payment_payers', 'payments', ['payment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payment_payers', 'users', ['user_id'], ['uid'], ondelete='CASCADE')
    op.create_index(op.f('ix_payment_splits_payment_id'), 'payment_splits', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_splits_user_id'), 'payment_splits', ['user_id'], unique=False)
    op.drop_constraint('payment_splits_payment_id_fkey', 'payment_splits', type_='foreignkey')
    op.drop_constraint('payment_splits_user_id_fkey', 'payment_splits', type_='foreignkey')
    op.create_foreign_key(None, 'payment_splits', 'payments', ['payment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payment_splits', 'users', ['user_id'], ['uid'], ondelete='CASCADE')
    op.create_index(op.f('ix_payments_owner'), 'payments', ['owner'], unique=False)
    op.create_index(op.f('ix_payments_project_id'), 'payments', ['project_id'], unique=False)
    op.drop_constraint('payments_owner_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_category_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_project_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['owner'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_project_editors_project_id'), 'project_editors', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_editors_user_id'), 'project_editors', ['user_id'], unique=False)
    op.drop_constraint('project_editors_project_id_fkey', 'project_editors', type_='foreignkey')
    op.drop_constraint('project_editors_user_id_fkey', 'project_editors', type_='foreignkey')
    op.create_foreign_key(None, 'project_editors', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_editors', 'users', ['user_id'], ['uid'], ondelete='CASCADE')
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.drop_constraint('project_members_user_id_fkey', 'project_members', type_='foreignkey')
    op.drop_constraint('project_members_project_id_fkey', 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_projects_owner'), 'projects', ['owner'], unique=False)
    op.drop_constraint('projects_owner_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_owner_fkey', 'projects', 'users', ['owner'], ['uid'])
    op.drop_index(op.f('ix_projects_owner'), table_name='projects')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key('project_members_project_id_fkey', 'project_members', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('project_members_user_id_fkey', 'project_members', 'users', ['user_id'], ['uid'])
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_constraint(None, 'project_editors', type_='foreignkey')
    op.drop_constraint(None, 'project_editors', type_='foreignkey')
    op.create_foreign_key('project_editors_user_id_fkey', 'project_editors', 'users', ['user_id'], ['uid'])
    op.create_foreign_key('project_editors_project_id_fkey', 'project_editors', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_project_editors_user_id'), table_name='project_editors')
    op.drop_index(op.f('ix_project_editors_project_id'), table_name='project_editors')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_project_id_fkey', 'payments', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('payments_category_id_fkey', 'payments', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('payments_owner_fkey', 'payments', 'users', ['owner'], ['uid'])
    op.drop_index(op.f('ix_payments_project_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_owner'), table_name='payments')
    op.drop_constraint(None, 'payment_splits', type_='foreignkey')
    op.drop_constraint(None, 'payment_splits', type_='foreignkey')
    op.create_foreign_key('payment_splits_user_id_fkey', 'payment_splits', 'users', ['user_id'], ['uid'])
    op.create_foreign_key('payment_splits_payment_id_fkey', 'payment_splits', 'payments', ['payment_id'], ['id'])
    op.drop_index(op.f('ix_payment_splits_user_id'), table_name='payment_splits')
    op.drop_index(op.f('ix_payment_splits_payment_id'), table_name='payment_splits')
    op.drop_constraint(None, 'payment_payers', type_='foreignkey')
    op.drop_constraint(None, 'payment_payers', type_='foreignkey')
    op.create_foreign_key('payment_payers_user_id_fkey', 'payment_payers', 'users', ['user_id'], ['uid'])
    op.create_foreign_key('payment_payers_payment_id_fkey', 'payment_payers', 'payments', ['payment_id'], ['id'])
    op.drop_index(op.f('ix_payment_payers_user_id'), table_name='payment_payers')
    op.drop_index(op.f('ix_payment_payers_payment_id'), table_name='payment_payers')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_payment_id_fkey', 'items', 'payments', ['payment_id'], ['id'])
    op.drop_index(op.f('ix_items_payment_id'), table_name='items')
    op.drop_constraint(None, 'item_splits', type_='foreignkey')
    op.drop_constraint(None, 'item_splits', type_='foreignkey')
    op.create_foreign_key('item_splits_item_id_fkey', 'item_splits', 'items', ['item_id'], ['id'])
    op.create_foreign_key('item_splits_user_id_fkey', 'item_splits', 'users', ['user_id'], ['uid'])
    op.drop_index(op.f('ix_item_splits_user_id'), table_name='item_splits')
    op.drop_index(op.f('ix_item_splits_item_id'), table_name='item_splits')
    # ### end Alembic commands ###
